'use strict';
const APP_VERSION = '1.1.0';
const FLOW = ['Prep', 'Photographed', 'Live', 'Sold', 'Dispatched', 'Archived'];
function money(n) { return new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(Number(n || 0)); }
function nextSku(items) { let max = 0; for (const x of items) {
    const m = String(x.sku || '').match(/(\d+)$/);
    if (m)
        max = Math.max(max, Number(m[1]));
} return `JAE-${String(max + 1).padStart(4, '0')}`; }
function metrics(items, orders) {
    const active = items.filter(x => !['Archived', 'Dispatched'].includes(x.status)).length;
    const cost = items.reduce((s, x) => s + Number(x.landedCost ?? x.purchasePrice ?? 0), 0);
    const profit = items.reduce((s, x) => s + Number(x.expectedProfit ?? (x.expectedSale - x.landedCost)), 0);
    return { active, cost, profit, prep: items.filter(x => x.status === 'Prep').length, photographed: items.filter(x => x.status === 'Photographed').length, live: items.filter(x => x.status === 'Live').length, old: items.filter(x => x.daysInStock > 60).length, missing: items.filter(x => !x.storage || x.storage === 'TBC').length, orders: orders.length };
}
function healthScore(items, orders) { const m = metrics(items, orders); let s = 100; s -= Math.min(20, m.prep * 2); s -= Math.min(15, m.old); s -= Math.min(10, m.missing); s -= Math.min(10, orders.filter(x => x.deadline === 'Today').length * 3); return Math.max(45, Math.round(s)); }
function advanceStatus(item) { const i = FLOW.indexOf(item.status); const next = FLOW[Math.min(FLOW.length - 1, Math.max(0, i + 1))] ?? item.status; return { ...item, status: next, action: next === 'Photographed' ? 'Create listing' : next === 'Live' ? 'Monitor listing' : next === 'Sold' ? 'Pack order' : next === 'Dispatched' ? 'Archive sale' : 'Complete' }; }
function sourceCheck(buy, sale, condition, auth) { const conservative = sale * .82, profit = sale - buy - 1.5, conservativeProfit = conservative - buy - 1.5, roi = buy ? profit / buy : 0; let score = 45 + Math.min(22, Math.max(0, profit)) + Math.min(16, Math.max(0, roi * 4)) + (condition === 'Excellent' ? 12 : condition === 'Very good' ? 8 : condition === 'Good' ? 2 : -25) + (auth === 'High' ? 5 : auth === 'Medium' ? 0 : -30); score = Math.max(0, Math.min(100, Math.round(score))); let decision = score >= 85 ? 'BUY' : score >= 70 ? 'BUY SELECTIVELY' : score >= 55 ? 'CAUTION' : 'PASS'; if (condition === 'Needs attention' || auth === 'Low' || conservativeProfit < 10 || buy > 10)
    decision = 'PASS'; return { decision, score, profit, conservativeProfit, roi, maxBuy: Math.max(0, Math.min(10, conservative - 1.5 - 15)) }; }
function normaliseData(raw, fallback) { return { version: APP_VERSION, items: Array.isArray(raw.items) ? raw.items : fallback.items, orders: Array.isArray(raw.orders) ? raw.orders : fallback.orders }; }

const KEY = 'jos-one-data-v1';
const SETTINGS_KEY = 'jos-one-settings-v1';
const defaultSettings = { minimumProfit: 15, targetRoi: 150, storageLocations: ['Box A1','Box A2','Box B1','Rail 1','Shelf 1'] };
function loadSettings(){ return { ...defaultSettings, ...(parse(localStorage.getItem(SETTINGS_KEY)) || {}) }; }
function saveSettings(v){ localStorage.setItem(SETTINGS_KEY, JSON.stringify(v)); }
const LEGACY_KEYS = ['jos-items-v06', 'jos-items-v05', 'jos-items-v04', 'jos-items-v03', 'jos-items-v02'];
const LEGACY_ORDER_KEYS = ['jos-orders-v06', 'jos-orders-v05', 'jos-orders-v04', 'jos-orders-v03', 'jos-orders-v02'];
function parse(value) { try {
    return value ? JSON.parse(value) : null;
}
catch {
    return null;
} }
function loadData(fallback) { const current = parse(localStorage.getItem(KEY)); if (current)
    return normaliseData(current, fallback); let items = fallback.items, orders = fallback.orders; for (const k of LEGACY_KEYS) {
    const v = parse(localStorage.getItem(k));
    if (Array.isArray(v)) {
        items = v;
        break;
    }
} for (const k of LEGACY_ORDER_KEYS) {
    const v = parse(localStorage.getItem(k));
    if (Array.isArray(v)) {
        orders = v;
        break;
    }
} const migrated = { version: APP_VERSION, items, orders }; saveData(migrated); return migrated; }
function saveData(data) { localStorage.setItem(KEY, JSON.stringify({ ...data, version: APP_VERSION })); }
function exportData(data) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }), a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `JOS-One-backup-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 500); }

const esc = (s) => String(s ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c] ?? c));
const today = () => new Intl.DateTimeFormat('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date());
const logo = (size = 54) => `<img class="logo" style="width:${size}px;height:${size}px" src="./the-jae-edit-logo.png" alt="The JAE Edit">`;
const header = (title) => `<header class="top"><div class="brand">${logo()}<div><div class="eyebrow">JOS One · Engineering ${APP_VERSION}</div><div class="title">${esc(title)}</div><div class="sub">${today()}</div></div></div></header>`;
const nav = (state) => `<div class="bottom"><nav class="nav">${[['home', '⌂', 'Home'], ['inventory', '▤', 'Inventory'], ['add', '＋', 'Add'], ['source', '⌕', 'SourceCheck'], ['orders', '▣', 'Orders']].map(([p, i, l]) => `<button data-page="${p}" class="${state.page === p ? 'active' : ''}"><span style="font-size:25px">${i}</span>${l}</button>`).join('')}</nav></div>`;
function missions(state) { const m = metrics(state.items, state.orders), tasks = []; if (state.orders.length)
    tasks.push({ label: `Pack or dispatch ${state.orders.length} orders`, time: state.orders.length * 6, page: 'orders', impact: 'Protect next-day dispatch' }); if (m.prep)
    tasks.push({ label: `Prepare ${Math.min(6, m.prep)} stock items`, time: Math.min(50, m.prep * 7), page: 'inventory', impact: 'Move stock to photography' }); if (m.photographed)
    tasks.push({ label: `List ${Math.min(6, m.photographed)} photographed items`, time: Math.min(60, m.photographed * 10), page: 'inventory', impact: 'Unlock expected profit' }); return tasks.length ? tasks : [{ label: 'Review ageing inventory', time: 25, page: 'inventory', impact: 'Protect cash and storage' }]; }
function homeView(state) { const m = metrics(state.items, state.orders), h = healthScore(state.items, state.orders), tasks = missions(state), time = tasks.reduce((s, t) => s + t.time, 0); return `${header('CEO Dashboard')}<main class="content"><div class="card health compact"><div><div class="eyebrow">Good evening, Nick</div><div class="score">${h}/100</div><span class="pill">● ${h >= 85 ? 'Strong' : h >= 70 ? 'Stable' : 'Needs attention'}</span></div>${logo(68)}</div><div class="card mission"><div class="eyebrow">CEO Mode · Two-Hour Plan</div><h2>${esc(tasks[0]?.label)}</h2><p>${esc(tasks[0]?.impact)}</p><div class="mission-plan">${tasks.map((t, i) => `<button data-page="${t.page}"><b>${i + 1}</b><span>${esc(t.label)}<small>${t.time} mins · ${esc(t.impact)}</small></span></button>`).join('')}</div><div class="mission-total"><span>Estimated session</span><b>${Math.floor(time / 60)}h ${time % 60}m</b></div><button class="btn full" data-page="${tasks[0]?.page}">Start First Task</button></div><div class="dashboard-row"><button class="mini-stat" data-page="inventory"><span>Active stock</span><b>${m.active}</b></button><button class="mini-stat" data-page="inventory"><span>Expected profit</span><b>${money(m.profit)}</b></button><button class="mini-stat" data-page="orders"><span>Orders</span><b>${state.orders.length}</b></button></div><div class="card"><div class="eyebrow">Needs attention</div>${m.prep ? `<div class="health-reason warn"><span>•</span>${m.prep} items awaiting preparation</div>` : ''}${m.photographed ? `<div class="health-reason warn"><span>•</span>${m.photographed} photographed but not live</div>` : ''}${m.old ? `<div class="health-reason bad"><span>!</span>${m.old} items over 60 days</div>` : ''}</div><button class="btn secondary full" data-settings>Settings & Backup</button><div class="release-stamp">Live build: JOS One Workflow ${APP_VERSION}</div></main>${nav(state)}`; }
function inventoryView(state) { let items = state.items.filter(x => { const q = state.query.toLowerCase(); return !q || [x.sku, x.brand, x.category, x.description, x.storage, x.size].join(' ').toLowerCase().includes(q); }); if (state.sort === 'profit')
    items = [...items].sort((a, b) => b.expectedProfit - a.expectedProfit); return `${header('Inventory Command Centre')}<main class="content"><input id="search" class="search" placeholder="Search SKU, brand, item or location" value="${esc(state.query)}"><div class="toolbar"><button class="btn secondary" data-sort="profit">Sort by profit</button><button class="btn secondary" data-page="add">Add stock</button></div><div class="list">${items.map((x, i) => `<button class="item-card" data-item="${state.items.indexOf(x)}"><div><div class="eyebrow">${esc(x.sku)}</div><h3>${esc(x.brand)} ${esc(x.category)}</h3><div class="meta">${esc(x.description)} · ${esc(x.size || 'Size TBC')}<br>${esc(x.status)} · ${esc(x.storage)}</div></div><div class="right"><b>${money(x.expectedProfit)}</b><span class="grade">${esc(x.grade)}</span></div></button>`).join('') || '<div class="empty">No matching stock.</div>'}</div></main>${nav(state)}`; }
function stockForm(item) { const locations = loadSettings().storageLocations || []; return `<form id="stockForm" class="form"><input type="hidden" name="sku" value="${esc(item?.sku || '')}"><label>Brand<input required name="brand" value="${esc(item?.brand || '')}" autocomplete="off"></label><label>Category<select name="category">${['Hoodie', 'T-Shirt', 'Jacket', 'Jeans', 'Jumper', 'Fleece', 'Quarter Zip', 'Other'].map(v => `<option ${item?.category === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Size<input name="size" value="${esc(item?.size || '')}"></label><label>Condition<select name="condition">${['Excellent', 'Very good', 'Good', 'Satisfactory', 'Needs attention'].map(v => `<option ${item?.condition === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Purchase price<input required type="number" inputmode="decimal" step="0.01" name="purchase" value="${item?.purchasePrice ?? ''}"></label><label>Expected sale<input required type="number" inputmode="decimal" step="0.01" name="sale" value="${item?.expectedSale ?? ''}"></label><label>Storage<input name="storage" list="storageLocations" value="${esc(item?.storage || '')}" placeholder="Box A1"><datalist id="storageLocations">${locations.map(x=>`<option value="${esc(x)}">`).join('')}</datalist></label><details class="optional-fields" ${item ? 'open' : ''}><summary>More details</summary><label>Description<input name="description" value="${esc(item?.description || '')}"></label><label>Status<select name="status">${['Prep', 'Photographed', 'Live', 'Sold', 'Dispatched', 'Archived'].map(v => `<option ${item?.status === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Grade<select name="grade">${['A', 'B', 'C', 'Exit'].map(v => `<option ${item?.grade === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Source<input name="source" value="${esc(item?.source || '')}"></label></details><button class="btn full" type="submit">${item ? 'Save Changes' : 'Quick Add Stock'}</button></form>`; }
const addView = (state) => `${header('Quick Add Stock')}<main class="content"><div class="card"><div class="eyebrow">Target: under 30 seconds</div><h2>Capture the essentials</h2><p class="meta">SKU, profit and dashboard totals update automatically.</p>${stockForm()}</div></main>${nav(state)}`;
const sourceView = (state) => `${header('SourceCheck')}<main class="content"><div class="card"><form id="sourceForm" class="form"><label>Brand<input required name="brand"></label><label>Category<select name="category"><option>Hoodie</option><option>Jacket</option><option>Jeans</option><option>T-Shirt</option><option>Other</option></select></label><label>Condition<select name="condition"><option>Excellent</option><option>Very good</option><option>Good</option><option>Needs attention</option></select></label><label>Authenticity confidence<select name="auth"><option>High</option><option>Medium</option><option>Low</option></select></label><label>Buy price<input required type="number" inputmode="decimal" step="0.01" name="buy"></label><label>Expected sale<input required type="number" inputmode="decimal" step="0.01" name="sale"></label><button class="btn full">Analyse Item</button></form><div id="sourceResult"></div></div></main>${nav(state)}`;
const ordersView = (state) => `${header('Orders & Dispatch')}<main class="content"><h2 class="section-title">Order Queue</h2>${state.orders.map((o, i) => `<div class="card"><div class="item"><div><h3>${esc(o.item)}</h3><div class="meta">${esc(o.id)} · ${esc(o.sku)}<br>Deadline: ${esc(o.deadline)}</div></div><button class="btn secondary" data-dispatch="${i}">Complete</button></div></div>`).join('') || '<div class="empty">No active orders.</div>'}<div class="card"><button class="btn secondary" data-export>Download Backup</button></div></main>${nav(state)}`;
function itemModal(item, index) { return `<div class="modal" id="modal"><div class="sheet"><button class="close" data-close>×</button><div class="eyebrow">${esc(item.sku)}</div><h2 class="modal-title">${esc(item.brand)} ${esc(item.category)}</h2><p class="meta">${esc(item.description)}</p><div class="grid"><div class="metric"><span>Landed Cost</span><b>${money(item.landedCost)}</b></div><div class="metric"><span>Expected Profit</span><b>${money(item.expectedProfit)}</b></div><div class="metric"><span>Status</span><b class="metric-text">${esc(item.status)}</b></div><div class="metric"><span>Storage</span><b class="metric-text">${esc(item.storage)}</b></div></div><div class="quick-actions"><button class="btn full" data-advance="${index}">Advance Lifecycle</button><button class="btn secondary" data-listing="${index}">Create Listing</button><button class="btn secondary" data-edit="${index}">Edit</button><button class="btn danger" data-delete="${index}">Delete</button></div></div></div>`; }
function editModal(item, index) { return `<div class="modal" id="modal"><div class="sheet"><button class="close" data-close>×</button><div class="eyebrow">Edit ${esc(item.sku)}</div><h2 class="modal-title">Update stock item</h2><div data-edit-index="${index}">${stockForm(item)}</div></div></div>`; }

function listingDraft(item){ const title = `${item.brand} ${item.category} ${item.size ? '- ' + item.size : ''}`.trim(); const condition = item.condition || 'Very good'; const description = `${item.brand} ${item.category} in ${condition.toLowerCase()} condition. Carefully inspected and ready to wear.\n\nDetails:\n• Brand: ${item.brand}\n• Size: ${item.size || 'Please see label/photos'}\n• Condition: ${condition}\n• Storage SKU: ${item.sku}\n\nFast dispatch. Open to sensible offers. Bundle items to save on postage.`; return {title, description}; }
function listingModal(item){ const d=listingDraft(item); return `<div class="modal" id="modal"><div class="sheet"><button class="close" data-close>×</button><div class="eyebrow">Listing Assistant</div><h2 class="modal-title">Draft ready</h2><label>Title<textarea id="listingTitle" rows="2">${esc(d.title)}</textarea></label><label>Description<textarea id="listingDescription" rows="12">${esc(d.description)}</textarea></label><button class="btn full" data-copy-listing>Copy Listing</button></div></div>`; }
function settingsModal(){ const st=loadSettings(); return `<div class="modal" id="modal"><div class="sheet"><button class="close" data-close>×</button><div class="eyebrow">JOS Settings</div><h2 class="modal-title">Business defaults</h2><form id="settingsForm" class="form"><label>Minimum profit (£)<input type="number" inputmode="decimal" name="minimumProfit" value="${st.minimumProfit}"></label><label>Target ROI (%)<input type="number" inputmode="numeric" name="targetRoi" value="${st.targetRoi}"></label><label>Storage locations<textarea name="storageLocations" rows="6">${esc(st.storageLocations.join('\n'))}</textarea></label><button class="btn full">Save Settings</button></form><button class="btn secondary full" data-export>Download Backup</button></div></div>`; }
const defaultOrders = [{ id: 'ORD-1001', sku: 'JAE-PRE-006', item: 'Nike Blue/Gold Hoodie', status: 'Ready to pack', deadline: 'Tomorrow' }, { id: 'ORD-1002', sku: 'JAE-PRE-004', item: 'Tommy Womens T-Shirt', status: 'Ready to dispatch', deadline: 'Today' }];
const fallback = { version: APP_VERSION, items: window.JOS_SEED_ITEMS ?? [], orders: defaultOrders };
const loaded = loadData(fallback);
const state = { ...loaded, page: 'home', query: '', filter: 'All', sort: 'newest', toast: '' };
const rootEl = document.querySelector('#app');
if (!rootEl)
    throw new Error('Missing #app');
const root = rootEl;
function save() { saveData({ version: APP_VERSION, items: state.items, orders: state.orders }); }
function render() { const views = { home: homeView, inventory: inventoryView, add: addView, source: sourceView, orders: ordersView }; root.innerHTML = `<div class="app">${views[state.page](state)}</div>${state.toast ? `<div class="toast">${state.toast}</div>` : ''}`; bind(); }
function itemFromForm(form, existing) { const f = new FormData(form), purchase = Number(f.get('purchase')), sale = Number(f.get('sale')); return { ...existing, sku: String(f.get('sku') || existing?.sku || nextSku(state.items)), brand: String(f.get('brand') || '').trim(), category: String(f.get('category')), description: String(f.get('description') || '').trim() || `${f.get('brand')} ${f.get('category')}`, size: String(f.get('size') || ''), condition: String(f.get('condition')), status: String(f.get('status') || existing?.status || 'Prep'), grade: String(f.get('grade') || existing?.grade || 'B'), storage: String(f.get('storage') || 'TBC') || 'TBC', source: String(f.get('source') || ''), purchasePrice: purchase, landedCost: purchase, expectedSale: sale, listPrice: sale, expectedProfit: sale - purchase, roi: purchase ? (sale - purchase) / purchase : 0, daysInStock: existing?.daysInStock ?? 0, action: existing?.action ?? 'Prepare item' }; }
function bind() { document.querySelectorAll('[data-page]').forEach(b => b.onclick = () => { state.page = b.dataset.page; render(); }); const search = document.querySelector('#search'); if (search)
    search.oninput = () => { state.query = search.value; render(); }; document.querySelectorAll('[data-sort]').forEach(b => b.onclick = () => { state.sort = b.dataset.sort || 'newest'; render(); }); document.querySelectorAll('[data-item]').forEach(b => b.onclick = () => { const i = Number(b.dataset.item); document.body.insertAdjacentHTML('beforeend', itemModal(state.items[i], i)); bind(); }); document.querySelectorAll('[data-close]').forEach(b => b.onclick = () => document.querySelector('#modal')?.remove()); const stock = document.querySelector('#stockForm'); if (stock)
    stock.onsubmit = e => { e.preventDefault(); const wrapper = stock.closest('[data-edit-index]'); if (wrapper) {
        const i = Number(wrapper.dataset.editIndex), existing = state.items[i];
        if (existing) {
            state.items[i] = itemFromForm(stock, existing);
            save();
            document.querySelector('#modal')?.remove();
            state.toast = `${state.items[i]?.sku} updated successfully`;
            render();
            return;
        }
    } state.items.unshift(itemFromForm(stock)); save(); state.page = 'inventory'; state.toast = 'Stock added successfully'; render(); }; const source = document.querySelector('#sourceForm'); if (source)
    source.onsubmit = e => { e.preventDefault(); const f = new FormData(source), r = sourceCheck(Number(f.get('buy')), Number(f.get('sale')), String(f.get('condition')), String(f.get('auth'))); const target = document.querySelector('#sourceResult'); if (target)
        target.innerHTML = `<div class="card result ${r.decision === 'BUY' ? 'buy' : r.decision === 'PASS' ? 'pass' : 'caution'}"><div class="eyebrow">SourceCheck result</div><div class="decision">${r.decision}</div><div class="score">${r.score}/100</div><div class="result-grid"><div><span>Expected profit</span><b>£${r.profit.toFixed(2)}</b></div><div><span>Conservative profit</span><b>£${r.conservativeProfit.toFixed(2)}</b></div><div><span>Maximum buy</span><b>£${r.maxBuy.toFixed(2)}</b></div><div><span>ROI</span><b>${Math.round(r.roi * 100)}%</b></div></div></div>`; }; document.querySelectorAll('[data-edit]').forEach(b => b.onclick = () => { const i = Number(b.dataset.edit); const item = state.items[i]; if (!item)
    return; document.querySelector('#modal')?.remove(); document.body.insertAdjacentHTML('beforeend', editModal(item, i)); bind(); }); document.querySelectorAll('[data-advance]').forEach(b => b.onclick = () => { const i = Number(b.dataset.advance); state.items[i] = advanceStatus(state.items[i]); save(); document.querySelector('#modal')?.remove(); state.toast = `${state.items[i]?.sku} moved to ${state.items[i]?.status}`; render(); }); document.querySelectorAll('[data-delete]').forEach(b => b.onclick = () => { const i = Number(b.dataset.delete); if (confirm(`Delete ${state.items[i]?.sku}?`)) {
    state.items.splice(i, 1);
    save();
    document.querySelector('#modal')?.remove();
    render();
} }); document.querySelectorAll('[data-dispatch]').forEach(b => b.onclick = () => { const i = Number(b.dataset.dispatch), order = state.orders[i]; const item = state.items.find(x => x.sku === order?.sku); if (item)
    item.status = 'Dispatched'; state.orders.splice(i, 1); save(); state.toast = 'Order completed'; render(); }); document.querySelectorAll('[data-listing]').forEach(b => b.onclick = () => { const i=Number(b.dataset.listing), item=state.items[i]; if(!item) return; document.querySelector('#modal')?.remove(); document.body.insertAdjacentHTML('beforeend', listingModal(item)); bind(); }); document.querySelectorAll('[data-copy-listing]').forEach(b => b.onclick = async () => { const t=document.querySelector('#listingTitle')?.value || '', d=document.querySelector('#listingDescription')?.value || ''; await navigator.clipboard.writeText(`${t}\n\n${d}`); state.toast='Listing copied'; document.querySelector('#modal')?.remove(); render(); }); document.querySelectorAll('[data-settings]').forEach(b => b.onclick = () => { document.body.insertAdjacentHTML('beforeend', settingsModal()); bind(); }); const settingsForm=document.querySelector('#settingsForm'); if(settingsForm) settingsForm.onsubmit=e=>{ e.preventDefault(); const f=new FormData(settingsForm); saveSettings({ minimumProfit:Number(f.get('minimumProfit'))||15, targetRoi:Number(f.get('targetRoi'))||150, storageLocations:String(f.get('storageLocations')||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean) }); document.querySelector('#modal')?.remove(); state.toast='Settings saved'; render(); }; document.querySelectorAll('[data-export]').forEach(b => b.onclick = () => exportData({ version: APP_VERSION, items: state.items, orders: state.orders, settings: loadSettings() })); }
render();
if ('serviceWorker' in navigator)
    window.addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js').catch(console.warn));
