import { APP_VERSION, healthScore, metrics, money } from './domain.js';
const esc = (s) => String(s ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c] ?? c));
const today = () => new Intl.DateTimeFormat('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date());
const logo = (size = 54) => `<img class="logo" style="width:${size}px;height:${size}px" src="./the-jae-edit-logo.png" alt="The JAE Edit">`;
const header = (title) => `<header class="top"><div class="brand">${logo()}<div><div class="eyebrow">JOS One · Engineering ${APP_VERSION}</div><div class="title">${esc(title)}</div><div class="sub">${today()}</div></div></div></header>`;
const nav = (state) => `<div class="bottom"><nav class="nav">${[['home', '⌂', 'Home'], ['inventory', '▤', 'Inventory'], ['add', '＋', 'Add'], ['source', '⌕', 'SourceCheck'], ['orders', '▣', 'Orders']].map(([p, i, l]) => `<button data-page="${p}" class="${state.page === p ? 'active' : ''}"><span style="font-size:25px">${i}</span>${l}</button>`).join('')}</nav></div>`;
function missions(state) { const m = metrics(state.items, state.orders), tasks = []; if (state.orders.length)
    tasks.push({ label: `Pack or dispatch ${state.orders.length} orders`, time: state.orders.length * 6, page: 'orders', impact: 'Protect next-day dispatch' }); if (m.prep)
    tasks.push({ label: `Prepare ${Math.min(6, m.prep)} stock items`, time: Math.min(50, m.prep * 7), page: 'inventory', impact: 'Move stock to photography' }); if (m.photographed)
    tasks.push({ label: `List ${Math.min(6, m.photographed)} photographed items`, time: Math.min(60, m.photographed * 10), page: 'inventory', impact: 'Unlock expected profit' }); return tasks.length ? tasks : [{ label: 'Review ageing inventory', time: 25, page: 'inventory', impact: 'Protect cash and storage' }]; }
export function homeView(state) { const m = metrics(state.items, state.orders), h = healthScore(state.items, state.orders), tasks = missions(state), time = tasks.reduce((s, t) => s + t.time, 0); return `${header('CEO Dashboard')}<main class="content"><div class="card health compact"><div><div class="eyebrow">Good evening, Nick</div><div class="score">${h}/100</div><span class="pill">● ${h >= 85 ? 'Strong' : h >= 70 ? 'Stable' : 'Needs attention'}</span></div>${logo(68)}</div><div class="card mission"><div class="eyebrow">CEO Mode · Two-Hour Plan</div><h2>${esc(tasks[0]?.label)}</h2><p>${esc(tasks[0]?.impact)}</p><div class="mission-plan">${tasks.map((t, i) => `<button data-page="${t.page}"><b>${i + 1}</b><span>${esc(t.label)}<small>${t.time} mins · ${esc(t.impact)}</small></span></button>`).join('')}</div><div class="mission-total"><span>Estimated session</span><b>${Math.floor(time / 60)}h ${time % 60}m</b></div><button class="btn full" data-page="${tasks[0]?.page}">Start First Task</button></div><div class="dashboard-row"><button class="mini-stat" data-page="inventory"><span>Active stock</span><b>${m.active}</b></button><button class="mini-stat" data-page="inventory"><span>Expected profit</span><b>${money(m.profit)}</b></button><button class="mini-stat" data-page="orders"><span>Orders</span><b>${state.orders.length}</b></button></div><div class="card"><div class="eyebrow">Needs attention</div>${m.prep ? `<div class="health-reason warn"><span>•</span>${m.prep} items awaiting preparation</div>` : ''}${m.photographed ? `<div class="health-reason warn"><span>•</span>${m.photographed} photographed but not live</div>` : ''}${m.old ? `<div class="health-reason bad"><span>!</span>${m.old} items over 60 days</div>` : ''}</div><div class="release-stamp">Live build: JOS One Engineering ${APP_VERSION}</div></main>${nav(state)}`; }
export function inventoryView(state) { let items = state.items.filter(x => { const q = state.query.toLowerCase(); return !q || [x.sku, x.brand, x.category, x.description, x.storage, x.size].join(' ').toLowerCase().includes(q); }); if (state.sort === 'profit')
    items = [...items].sort((a, b) => b.expectedProfit - a.expectedProfit); return `${header('Inventory Command Centre')}<main class="content"><input id="search" class="search" placeholder="Search SKU, brand, item or location" value="${esc(state.query)}"><div class="toolbar"><button class="btn secondary" data-sort="profit">Sort by profit</button><button class="btn secondary" data-page="add">Add stock</button></div><div class="list">${items.map((x, i) => `<button class="item-card" data-item="${state.items.indexOf(x)}"><div><div class="eyebrow">${esc(x.sku)}</div><h3>${esc(x.brand)} ${esc(x.category)}</h3><div class="meta">${esc(x.description)} · ${esc(x.size || 'Size TBC')}<br>${esc(x.status)} · ${esc(x.storage)}</div></div><div class="right"><b>${money(x.expectedProfit)}</b><span class="grade">${esc(x.grade)}</span></div></button>`).join('') || '<div class="empty">No matching stock.</div>'}</div></main>${nav(state)}`; }
export function stockForm(item) { return `<form id="stockForm" class="form"><input type="hidden" name="sku" value="${esc(item?.sku || '')}"><label>Brand<input required name="brand" value="${esc(item?.brand || '')}"></label><label>Category<select name="category">${['Hoodie', 'T-Shirt', 'Jacket', 'Jeans', 'Jumper', 'Fleece', 'Quarter Zip', 'Other'].map(v => `<option ${item?.category === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Description<input name="description" value="${esc(item?.description || '')}"></label><label>Size<input name="size" value="${esc(item?.size || '')}"></label><label>Condition<select name="condition">${['Excellent', 'Very good', 'Good', 'Satisfactory', 'Needs attention'].map(v => `<option ${item?.condition === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Status<select name="status">${['Prep', 'Photographed', 'Live', 'Sold', 'Dispatched', 'Archived'].map(v => `<option ${item?.status === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Grade<select name="grade">${['A', 'B', 'C', 'Exit'].map(v => `<option ${item?.grade === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label>Purchase price<input required type="number" step="0.01" name="purchase" value="${item?.purchasePrice ?? ''}"></label><label>Expected sale<input required type="number" step="0.01" name="sale" value="${item?.expectedSale ?? ''}"></label><label>Storage<input name="storage" value="${esc(item?.storage || '')}"></label><label>Source<input name="source" value="${esc(item?.source || '')}"></label><button class="btn full" type="submit">Save Stock</button></form>`; }
export const addView = (state) => `${header('Add New Stock')}<main class="content"><div class="card"><div class="eyebrow">Fast stock entry</div><h2>Capture the essentials</h2>${stockForm()}</div></main>${nav(state)}`;
export const sourceView = (state) => `${header('SourceCheck')}<main class="content"><div class="card"><form id="sourceForm" class="form"><label>Brand<input required name="brand"></label><label>Category<select name="category"><option>Hoodie</option><option>Jacket</option><option>Jeans</option><option>T-Shirt</option><option>Other</option></select></label><label>Condition<select name="condition"><option>Excellent</option><option>Very good</option><option>Good</option><option>Needs attention</option></select></label><label>Authenticity confidence<select name="auth"><option>High</option><option>Medium</option><option>Low</option></select></label><label>Buy price<input required type="number" step="0.01" name="buy"></label><label>Expected sale<input required type="number" step="0.01" name="sale"></label><button class="btn full">Analyse Item</button></form><div id="sourceResult"></div></div></main>${nav(state)}`;
export const ordersView = (state) => `${header('Orders & Dispatch')}<main class="content"><h2 class="section-title">Order Queue</h2>${state.orders.map((o, i) => `<div class="card"><div class="item"><div><h3>${esc(o.item)}</h3><div class="meta">${esc(o.id)} · ${esc(o.sku)}<br>Deadline: ${esc(o.deadline)}</div></div><button class="btn secondary" data-dispatch="${i}">Complete</button></div></div>`).join('') || '<div class="empty">No active orders.</div>'}<div class="card"><button class="btn secondary" data-export>Download Backup</button></div></main>${nav(state)}`;
export function itemModal(item, index) { return `<div class="modal" id="modal"><div class="sheet"><button class="close" data-close>×</button><div class="eyebrow">${esc(item.sku)}</div><h2 class="modal-title">${esc(item.brand)} ${esc(item.category)}</h2><p class="meta">${esc(item.description)}</p><div class="grid"><div class="metric"><span>Landed Cost</span><b>${money(item.landedCost)}</b></div><div class="metric"><span>Expected Profit</span><b>${money(item.expectedProfit)}</b></div><div class="metric"><span>Status</span><b class="metric-text">${esc(item.status)}</b></div><div class="metric"><span>Storage</span><b class="metric-text">${esc(item.storage)}</b></div></div><div class="quick-actions"><button class="btn full" data-advance="${index}">Advance Lifecycle</button><button class="btn secondary" data-edit="${index}">Edit</button><button class="btn danger" data-delete="${index}">Delete</button></div></div></div>`; }
export function editModal(item, index) { return `<div class="modal" id="modal"><div class="sheet"><button class="close" data-close>×</button><div class="eyebrow">Edit ${esc(item.sku)}</div><h2 class="modal-title">Update stock item</h2><div data-edit-index="${index}">${stockForm(item)}</div></div></div>`; }
